# Tensors  
tensors are nothing but some kind of numpy arrays but with some extra powers like automatic differentiation

In [23]:
import torch
import numpy as np

In [4]:
x = torch.tensor(6) # 0D Tensor
x

torch.int64

In [5]:
y = torch.tensor([1, 2, 3]) # 1D Tensor
y

tensor([1, 2, 3])

In [8]:
z = torch.tensor([[1, 2, 3], 
                 [4, 5, 6]])  # 2D Tensor
z

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# They can calculate gradients automatically 
a = torch.tensor(5.0, requires_grad = True) # By Default False


5.0

In [17]:
torch.zeros(3)


tensor([0., 0., 0.])

In [18]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.rand(2,3) # Random values between 0 and 1

tensor([[0.5234, 0.0292, 0.4935],
        [0.9754, 0.1929, 0.0565]])

In [20]:
torch.randn(3) # Random normal

tensor([ 0.7197, -1.1809,  0.1383])

In [21]:
x.device

device(type='cpu')

In [24]:
a = np.array([1,2,3])

t = torch.tensor(a)

In [25]:
tnp = t.numpy()

In [28]:
tnp.dtype

dtype('int64')