In [26]:
import numpy as np

In [27]:
matrix_1D = np.array([1,2,3,4,5,10])

In [28]:
print(matrix_1D)

[ 1  2  3  4  5 10]


In [29]:
type(matrix_1D)

numpy.ndarray

In [30]:
print("Shape : ", matrix_1D.shape) # Returns a tuple representing the dimension

Shape :  (6,)


In [31]:
print("DataType: ", matrix_1D.dtype)

DataType:  int64


In [32]:
print("Dimensions : ", matrix_1D.ndim) # 1 for vector, 2 for matrix 

Dimensions :  1


In [33]:
matrix2 = np.array([[1,2,3],[4,5,6]])

In [34]:
print(matrix2)

[[1 2 3]
 [4 5 6]]


In [35]:
print(matrix2.shape)

(2, 3)


In [36]:
matrix3 = np.array([[2,5,7,9],
                   [1,9,0,1],
                   [7,0,4,2]])

In [37]:
print(matrix3.shape)
print(matrix3.ndim)
print(matrix3.dtype)

(3, 4)
2
int64


Every ndarray relies on three things to interpret that raw block of memory:

- **Data Pointer (data)**: The starting memory address of the block.
- **Shape**: The dimensions of the array (e.g., (3, 4)).
- **Strides**: A number of bytes to skip in each dimension to get to the next element. For example, jumping to the next column in a matrix takes 8 bytes, while jumping to the next row takes 32 bytes.

In [38]:
print("Strides : ", matrix3.strides)  # prints in terms of (Row, Column)

Strides :  (32, 8)


In [39]:
sub_matrix = matrix3[0:2, 0:2]

In [40]:
sub_matrix

array([[2, 5],
       [1, 9]])