In [1]:
import numpy as np

In [2]:
a = np.arange(1, 21)

In [3]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
matrix = a.reshape(5,4)

In [6]:
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [8]:
first_column = matrix[: , 0]

In [9]:
mask = (first_column % 2 != 0)

In [10]:
print(first_column[mask])

[ 1  5  9 13 17]
